package main;

/**
 * enum con las opciones posibles del programa
 * @author Maximiliano Valencia Saez
 */
public enum Opcion{
        AGREGAR, AGREGARSEDE, AGREGARMESA, AGREGARPERSONA, AGREGARDIRECCION,
        MOSTRAR, MOSTRARSEDES, MOSTRARSEDESYPERSONAS, MOSTRARSEDESMESASPERSONAS,
        EDITAR, EDITSEDE, EDITPERS, EDITMESA,
        ELIMINAR, ELIMINSEDE,
        BUSCAR, 
        REPORTAR, 
        GRAFICAR, 
        VENTANA, 
        SELECTXCRITERIO, SEDEMASPERS, SEDEMENOSPERS, PERSONAMASLEJOS,
        SUBCONJXFILTRO,  VOCCPART, VOCSPART, APOCPART, APOSPART,VOTMISMADIR,
        SALIR,
        SKIP,
        
}